package com.demo.booking.booking.domain.exception;

import com.demo.booking.common.exception.ErrorCode;

public enum BookingErrorCode implements ErrorCode {
    BOOKING_NOT_FOUND,
    BOOKING_ALREADY_CONFIRMED,
    BOOKING_ALREADY_CANCELLED,
    BOOKING_CANNOT_CANCEL,
    BOOKING_INVALID_STATUS,
    BOOKING_PAYMENT_FAILED,
    BOOKING_STOCK_INSUFFICIENT,
    BOOKING_USER_UNAUTHORIZED,
    BOOKING_IDEMPOTENCY_VIOLATION,
    BOOKING_EXPIRED,
    BOOKING_CANNOT_CONFIRM,
    BOOKING_CANNOT_MARK_FAILED,
    BOOKING_CANNOT_COMPLETE,
    BOOKING_INVALID_PAYMENT_ID,
    BOOKING_INVALID_DATES,
    BOOKING_INVALID_AMOUNT,
    BOOKING_STOCK_RESERVATION_FAILED,
    BOOKING_CREATION_FAILED,
    STOCK_HOLD_SERVICE_UNAVAILABLE,
    STOCK_HOLD_ERROR;

    @Override
    public String getCode() {
        return name();
    }
}